name: Linting Pipeline
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Debug HTMLHint Binary
      run: |
        echo "Checking if htmlhint is installed..."
        ls -l node_modules/.bin/htmlhint
        echo "Checking Node.js version..."
        node --version
        echo "Checking npm version..."
        npm --version
    - name: Set execute permissions for all binaries
      run: chmod -R +x node_modules/.bin
    - name: Lint HTML files
      run: ./node_modules/.bin/htmlhint "src/**/*.html"
    - name: Lint CSS files
      run: stylelint "styles/**/*.css"
